version: '3'

services:
  database:
    image: mariadb
    env_file:
      - ./variables.env
    #needed ?
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 5s
      retries: 20
    volumes:
      - 'lobsters_database:/var/lib/mysql'
  app:
    build:
      context: .
      args:
        developer_build: "false"
    ports:
      - "3000:3000"
    env_file:
      - ./variables.env
    depends_on:
      - database

volumes:
  lobsters_database:
    driver: local
